# Generated by Django 3.2.12 on 2022-03-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='имя')),
                ('url', models.URLField(verbose_name='ссылка')),
                ('old_price', models.FloatField(verbose_name='старая цена')),
                ('current_eur_price', models.FloatField(verbose_name='текущая цена EUR')),
                ('current_rub_price', models.FloatField(verbose_name='текущая цена RUB')),
            ],
            options={
                'verbose_name': 'видеокарта',
                'verbose_name_plural': 'видеокарты',
            },
        ),
    ]
