# Generated by Django 3.2.12 on 2022-03-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=200, verbose_name='имя')),
                ('is_active', models.BooleanField(default=False, verbose_name='учетная запись активирована')),
                ('min_price', models.FloatField(blank=True, null=True, verbose_name='минимальная цена видеокарты к показу')),
                ('max_price', models.FloatField(blank=True, null=True, verbose_name='максимальная цена видеокарты к показу')),
            ],
            options={
                'verbose_name': 'пльзователь телеграм',
                'verbose_name_plural': 'пользователи телеграма',
            },
        ),
    ]
