# Generated by Django 3.2.12 on 2022-03-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_telegramuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.CharField(max_length=200, verbose_name='телеграм id'),
        ),
    ]
