# Generated by Django 3.2.12 on 2022-03-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_telegramuser_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphiccard',
            name='current_rub_price',
            field=models.FloatField(blank=True, null=True, verbose_name='текущая цена RUB'),
        ),
        migrations.AlterField(
            model_name='graphiccard',
            name='old_price',
            field=models.FloatField(blank=True, null=True, verbose_name='старая цена'),
        ),
    ]
