# Generated by Django 3.2.12 on 2022-03-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_alter_graphiccard_price_was_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphiccard',
            name='price_was_updated',
            field=models.BooleanField(blank=True, default=False, verbose_name='цена была обновлена'),
        ),
    ]
